language: python

python:
  - "2.7"
  - "3.4"

install:
  - python setup.py install
  - pip install nose flake8 hacking

script:
  - nosetests -a '!gpu' tests/chainer_tests tests/functions_tests tests/optimizers_tests tests/testing_tests tests/utils_tests
  - flake8 chainer tests examples --exclude=libcudnn.py,caffe_pb2.py
