language: python

cache:
  - pip
  - ccache

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.5"
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=2.7.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
      if: (branch = master OR branch = v3) AND (NOT type in (pull_request))
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.5.1
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
      if: (branch = master OR branch = v3) AND (NOT type in (pull_request))

before_install:
  - if [[ $TRAVIS_OS_NAME = "osx" ]]; then
      brew update >/dev/null;
      rvm use ruby-2.3.3
      brew outdated pyenv || brew upgrade --quiet pyenv;
      brew install homebrew/boneyard/pyenv-pip-rehash;

      PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2" pyenv install -ks $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
      python --version;

      brew install homebrew/science/hdf5;
    fi
  - export LD_LIBRARY_PATH=$HOME/.chainer/lib:$HOME/.local/lib:/usr/local/lib
  - export LIBRARY_PATH=$LD_LIBRARY_PATH
  - export C_INCLUDE_PATH=$HOME/.chainer/include:$HOME/.local/include
  - export CPLUS_INCLUDE_PATH=$C_INCLUDE_PATH
  - export PATH="$HOME/.local/bin:/usr/local/cuda/bin/:$PATH"
  - wget https://nchc.dl.sourceforge.net/project/swig/swig/swig-3.0.12/swig-3.0.12.tar.gz
  - tar -xf swig-3.0.12.tar.gz
  - cd swig-3.0.12/
  - ./configure
  - make -j
  - sudo make install
  - cd ../
  - git clone https://github.com/google/glog
  - cd glog
  - ./autogen.sh
  - ./configure
  - make -j
  - sudo make install
  - cd ../


install:
  - pip install --upgrade pip
  - pip install h5py pillow protobuf
  - pip install nose hacking mock coveralls filelock


script:
  - python setup.py install
  - cd tests
  - nosetests --cover-branches --with-coverage --cover-package=chainer -v -a '!gpu,!slow' chainer_tests


addons:
  apt:
    packages:
      - gfortran
      - libhdf5-serial-dev
      - liblapack-dev
      - libssl-dev
      - libboost-dev
      - libboost-system1.54

# coveralls
after_success:
     coveralls

